Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]
  #config.vbguest.auto_update = "vbguestupdate"


#Loadbalancer
  config.vm.define "klantnaam-LB" do |lb_config|
 
      lb_config.vm.box = "ubuntu/xenial64"
      lb_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

      lb_config.vm.hostname = "klantnaam-typeomgeving-LB"
      lb_config.vm.network "private_network", ip: "192.168.KLANTID.10"

      lb_config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.name = "klantnaam-typeomgeving-LB"
      end
  
  end

#WEBSERVER 1
(1..1).each do |i|
  config.vm.define "klantnaam-typeomgeving-typeomgeving-webserver#{i}" do |web1_config|
 
      web1_config.vm.box = "ubuntu/xenial64"
      web1_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

      web1_config.vm.hostname = "klantnaam-typeomgeving-Webserver#{i}"
      web1_config.vm.network "private_network", ip: "192.168.KLANDID.1#{i}"

      web1_config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.name = "klantnaam-typeomgeving-Webserver#{i}"
      end
  end
end

#DATABASESERVER 1
  config.vm.define "klantnaam-typeomgeving-dbserver1" do |db_config|
 
      db_config.vm.box = "ubuntu/xenial64"
      db_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

      db_config.vm.hostname = "klantnaam-typeomgeving-dbserver1"
      db_config.vm.network "private_network", ip: "192.168.KLANTID.15"

      db_config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.name = "klantnaam-typeomgeving-dbserver1"
      end
  
  end

end
